### ISSUE TITLE
图形学入门笔记中的向量部分有误

### ISSUE THREAD

**Issue by SADYX** [puxiao/notes#1]
[这里](https://github.com/puxiao/notes/blob/master/%E3%80%8A%E9%97%AB%E4%BB%A4%E7%90%AA-%E7%8E%B0%E4%BB%A3%E5%9B%BE%E5%BD%A2%E5%AD%A6%E5%85%A5%E9%97%A8%E3%80%8B%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0.md?plain=1#L181
)这部分应该为

>  _在我们描述一个单位向量时，通常只关心它的方向。_

**Comment by puxiao** [comment]
GLTM
