### ISSUE TITLE
哥们你这学习经历太牛了，我都学2年半了，还只会vue3/2、react、nginx、docker、linux基础命令

### ISSUE THREAD

**Issue by moon-in-river** [puxiao/notes#3]

**Comment by moon-in-river** [comment]
老哥，能分享下你的学习策略吗，上班一年半基本没学啥新技术了。

**Comment by puxiao** [comment]
这说明你工作内容没变化，用已有的知识即可应付日常工作。

* 要么你寻找个新方向的工作，自然就需要学习新的知识，技术栈。

  > 但是目前就业行情不好，肯定不建议你换工作。

* 要么你利用闲暇之余，定一个新目标方向，去学习这个新方向涉及到的新知识。



<br>

一定是先有了需求，才有学习方向和动力。

另外培养一下自己的写作能力，给自己找点学习乐趣。

**Comment by moon-in-river** [comment]
确实目前知识足够应对日常工作了，感谢老哥分享
